#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SunnyDay.Client.Droid.Resource", IsApplication=true)]

namespace SunnyDay.Client.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::SunnyDay.Client.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::SunnyDay.Client.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::SunnyDay.Client.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::SunnyDay.Client.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::SunnyDay.Client.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::SunnyDay.Client.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::SunnyDay.Client.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::SunnyDay.Client.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::SunnyDay.Client.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::SunnyDay.Client.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::SunnyDay.Client.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::SunnyDay.Client.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::SunnyDay.Client.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::SunnyDay.Client.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::SunnyDay.Client.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::SunnyDay.Client.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::SunnyDay.Client.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::SunnyDay.Client.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::SunnyDay.Client.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::SunnyDay.Client.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::SunnyDay.Client.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::SunnyDay.Client.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::SunnyDay.Client.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::SunnyDay.Client.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::SunnyDay.Client.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiCentered = global::SunnyDay.Client.Droid.Resource.Attribute.vpiCentered;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiCirclePageIndicatorStyle = global::SunnyDay.Client.Droid.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiFillColor = global::SunnyDay.Client.Droid.Resource.Attribute.vpiFillColor;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiOrientation = global::SunnyDay.Client.Droid.Resource.Attribute.vpiOrientation;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiPageColor = global::SunnyDay.Client.Droid.Resource.Attribute.vpiPageColor;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiRadius = global::SunnyDay.Client.Droid.Resource.Attribute.vpiRadius;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiSnap = global::SunnyDay.Client.Droid.Resource.Attribute.vpiSnap;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiStrokeColor = global::SunnyDay.Client.Droid.Resource.Attribute.vpiStrokeColor;
			global::CarouselView.FormsPlugin.Android.Resource.Attribute.vpiStrokeWidth = global::SunnyDay.Client.Droid.Resource.Attribute.vpiStrokeWidth;
			global::CarouselView.FormsPlugin.Android.Resource.Boolean.default_circle_indicator_centered = global::SunnyDay.Client.Droid.Resource.Boolean.default_circle_indicator_centered;
			global::CarouselView.FormsPlugin.Android.Resource.Boolean.default_circle_indicator_snap = global::SunnyDay.Client.Droid.Resource.Boolean.default_circle_indicator_snap;
			global::CarouselView.FormsPlugin.Android.Resource.Color.default_circle_indicator_fill_color = global::SunnyDay.Client.Droid.Resource.Color.default_circle_indicator_fill_color;
			global::CarouselView.FormsPlugin.Android.Resource.Color.default_circle_indicator_page_color = global::SunnyDay.Client.Droid.Resource.Color.default_circle_indicator_page_color;
			global::CarouselView.FormsPlugin.Android.Resource.Color.default_circle_indicator_stroke_color = global::SunnyDay.Client.Droid.Resource.Color.default_circle_indicator_stroke_color;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__background_holo_dark = global::SunnyDay.Client.Droid.Resource.Color.vpi__background_holo_dark;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__background_holo_light = global::SunnyDay.Client.Droid.Resource.Color.vpi__background_holo_light;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_disabled_holo_dark = global::SunnyDay.Client.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_dark;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_disabled_holo_light = global::SunnyDay.Client.Droid.Resource.Color.vpi__bright_foreground_disabled_holo_light;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_holo_dark = global::SunnyDay.Client.Droid.Resource.Color.vpi__bright_foreground_holo_dark;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_holo_light = global::SunnyDay.Client.Droid.Resource.Color.vpi__bright_foreground_holo_light;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_inverse_holo_dark = global::SunnyDay.Client.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_dark;
			global::CarouselView.FormsPlugin.Android.Resource.Color.vpi__bright_foreground_inverse_holo_light = global::SunnyDay.Client.Droid.Resource.Color.vpi__bright_foreground_inverse_holo_light;
			global::CarouselView.FormsPlugin.Android.Resource.Dimension.default_circle_indicator_radius = global::SunnyDay.Client.Droid.Resource.Dimension.default_circle_indicator_radius;
			global::CarouselView.FormsPlugin.Android.Resource.Dimension.default_circle_indicator_stroke_width = global::SunnyDay.Client.Droid.Resource.Dimension.default_circle_indicator_stroke_width;
			global::CarouselView.FormsPlugin.Android.Resource.Id.horizontal = global::SunnyDay.Client.Droid.Resource.Id.horizontal;
			global::CarouselView.FormsPlugin.Android.Resource.Id.indicator = global::SunnyDay.Client.Droid.Resource.Id.indicator;
			global::CarouselView.FormsPlugin.Android.Resource.Id.pager = global::SunnyDay.Client.Droid.Resource.Id.pager;
			global::CarouselView.FormsPlugin.Android.Resource.Id.vertical = global::SunnyDay.Client.Droid.Resource.Id.vertical;
			global::CarouselView.FormsPlugin.Android.Resource.Integer.default_circle_indicator_orientation = global::SunnyDay.Client.Droid.Resource.Integer.default_circle_indicator_orientation;
			global::CarouselView.FormsPlugin.Android.Resource.Layout.vertical_viewpager = global::SunnyDay.Client.Droid.Resource.Layout.vertical_viewpager;
			global::CarouselView.FormsPlugin.Android.Resource.Layout.viewpager = global::SunnyDay.Client.Droid.Resource.Layout.viewpager;
			global::CarouselView.FormsPlugin.Android.Resource.Style.Theme_PageIndicatorDefaults = global::SunnyDay.Client.Droid.Resource.Style.Theme_PageIndicatorDefaults;
			global::CarouselView.FormsPlugin.Android.Resource.Style.Widget = global::SunnyDay.Client.Droid.Resource.Style.Widget;
			global::CarouselView.FormsPlugin.Android.Resource.Style.Widget_CirclePageIndicator = global::SunnyDay.Client.Droid.Resource.Style.Widget_CirclePageIndicator;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator = global::SunnyDay.Client.Droid.Resource.Styleable.CirclePageIndicator;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiCentered = global::SunnyDay.Client.Droid.Resource.Styleable.CirclePageIndicator_vpiCentered;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiFillColor = global::SunnyDay.Client.Droid.Resource.Styleable.CirclePageIndicator_vpiFillColor;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiOrientation = global::SunnyDay.Client.Droid.Resource.Styleable.CirclePageIndicator_vpiOrientation;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiPageColor = global::SunnyDay.Client.Droid.Resource.Styleable.CirclePageIndicator_vpiPageColor;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiRadius = global::SunnyDay.Client.Droid.Resource.Styleable.CirclePageIndicator_vpiRadius;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiSnap = global::SunnyDay.Client.Droid.Resource.Styleable.CirclePageIndicator_vpiSnap;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiStrokeColor = global::SunnyDay.Client.Droid.Resource.Styleable.CirclePageIndicator_vpiStrokeColor;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.CirclePageIndicator_vpiStrokeWidth = global::SunnyDay.Client.Droid.Resource.Styleable.CirclePageIndicator_vpiStrokeWidth;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.ViewPagerIndicator = global::SunnyDay.Client.Droid.Resource.Styleable.ViewPagerIndicator;
			global::CarouselView.FormsPlugin.Android.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::SunnyDay.Client.Droid.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
			global::Microsoft.WindowsAzure.Mobile.Files.Resource.String.ApplicationName = global::SunnyDay.Client.Droid.Resource.String.ApplicationName;
			global::Microsoft.WindowsAzure.Mobile.Files.Resource.String.Hello = global::SunnyDay.Client.Droid.Resource.String.Hello;
			global::PCLStorage.Resource.String.ApplicationName = global::SunnyDay.Client.Droid.Resource.String.ApplicationName;
			global::PCLStorage.Resource.String.Hello = global::SunnyDay.Client.Droid.Resource.String.Hello;
			global::Splat.Resource.String.library_name = global::SunnyDay.Client.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000c
			public const int ahBarColor = 2130771980;
			
			// aapt resource value: 0x7f010014
			public const int ahBarLength = 2130771988;
			
			// aapt resource value: 0x7f010013
			public const int ahBarWidth = 2130771987;
			
			// aapt resource value: 0x7f010011
			public const int ahCircleColor = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int ahDelayMillis = 2130771984;
			
			// aapt resource value: 0x7f010012
			public const int ahRadius = 2130771986;
			
			// aapt resource value: 0x7f01000d
			public const int ahRimColor = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int ahRimWidth = 2130771982;
			
			// aapt resource value: 0x7f01000f
			public const int ahSpinSpeed = 2130771983;
			
			// aapt resource value: 0x7f010009
			public const int ahText = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int ahTextColor = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int ahTextSize = 2130771979;
			
			// aapt resource value: 0x7f010001
			public const int vpiCentered = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010006
			public const int vpiFillColor = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int vpiOrientation = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int vpiPageColor = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int vpiRadius = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int vpiSnap = 2130771972;
			
			// aapt resource value: 0x7f010007
			public const int vpiStrokeColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int vpiStrokeWidth = 2130771976;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int default_circle_indicator_centered = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int default_circle_indicator_snap = 2131099649;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int default_circle_indicator_fill_color = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int default_circle_indicator_page_color = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int default_circle_indicator_stroke_color = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int vpi__background_holo_dark = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int vpi__background_holo_light = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int vpi__bright_foreground_disabled_holo_dark = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int vpi__bright_foreground_disabled_holo_light = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int vpi__bright_foreground_holo_dark = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int vpi__bright_foreground_holo_light = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int vpi__bright_foreground_inverse_holo_dark = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int vpi__bright_foreground_inverse_holo_light = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_radius = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_circle_indicator_stroke_width = 2131230721;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_errorstatus = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_successstatus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int roundedbg = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int roundedbgdark = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0000
			public const int horizontal = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int indicator = 2131361799;
			
			// aapt resource value: 0x7f0a0004
			public const int loadingImage = 2131361796;
			
			// aapt resource value: 0x7f0a0002
			public const int loadingProgressBar = 2131361794;
			
			// aapt resource value: 0x7f0a0005
			public const int loadingProgressWheel = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int pager = 2131361798;
			
			// aapt resource value: 0x7f0a0003
			public const int textViewStatus = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int vertical = 2131361793;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_orientation = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int vertical_viewpager = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int viewpager = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int Theme_PageIndicatorDefaults = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int Widget = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int Widget_CirclePageIndicator = 2131296258;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_vpiCentered = 0;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_vpiFillColor = 5;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_vpiOrientation = 2;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_vpiPageColor = 1;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_vpiRadius = 4;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_vpiSnap = 3;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_vpiStrokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_vpiStrokeWidth = 7;
			
			public static int[] ProgressWheel = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
